### ISSUE TITLE
Reputations and daily emissaries (enhancement request)

### ISSUE THREAD

**Issue by Alyred** [chancedj/LockedOut#35] opened 2017-09-29 07:18 UTC
I would love to see the currency line turned into three tabs: Currency, Reputation, and Emissaries.

Regarding the Emissaries section, have a rolling active emissary list, showing the expiry date on hover. If a character has turned in the emissary for that row, mark it with an checkmark.

Reputation would be great if it were a collapsible list that remembered the state you set it in, and show the character reputations similar to how you have currencies configured (reputations that a particular character doesn't have appear as blank), color coded to denote level (Hated->Exalted) with hover text that displays the actual reputation level with that faction.

I put together a good hex color list that has a good range between each (for a spreadsheet I'm working on) so that they're pretty easy to denote, though color-blindness may need more options (future feature, perhaps?):

```
Rep         Hex Code  R   G   B
Hated       #E60000   230 0   0
Hostile     #EE6622   238 102 34
Unfriendly  #996621   153 102 33
Neutral     #999900   153 153 0
Friendly    #009900   0   153 0
Honored     #6D9EEB   109 158 235
Revered     #0070DD   0   112 221
Exalted     #A335EE   163 53  238

```
Here's how those look visually:

![image](https://user-images.githubusercontent.com/29611002/31004733-7e4ba774-a4aa-11e7-96eb-ff18634323a1.png)

**Comment by chancedj** [comment] 2017-09-29 13:39
thanks.  will look into adding this in.

**Comment by Alyred** [comment] 2017-09-30 05:37
Welcome!  I think the Emissary completion fits well within the addon's scope, and should probably take precedence over the reputations list, The reputations... not quite so much within the addon scope, but still would be handy when trying to decide who to send BoA tokens to.

Altoholic does have some of the reputation functionality in the grid section, but it's not as easy to read.

Thanks for your work on this addon.  It's looking great so far!

**Comment by Daeveren** [comment] 2017-09-30 09:29
Emissaries is indeed nice to have, most likely it will be used for the future expansions too, since it's an awesome system that works well.
Both the emissaries and reputation should have on/off toggles, not everyone would want to see them in the list. I am never interested in tracking the emissaries or reputation for my alts.

**Comment by chancedj** [comment] 2017-09-30 23:01
yes.  i'm not sure how the reputation tracking would work in the end.  it's not really a lockout based feature?  If we drop that, then it becomes a duplicate of #12.

**Comment by Alyred** [comment] 2017-10-01 19:20
Reputation tracking was somewhat outside of the scope, I'll admit. It was more for the ability to track paragon reputations and which characters to send BoA reputation tokens to. With the framework in place for currencies I was thinking it might not have been too difficult to add in.

**Comment by chancedj** [comment] 2017-10-03 03:55
ok.  1.5.0 currently has emmisary tracking. if you want paragon tracking, go ahead and put another request and and i'll see about possibly adding it.  that way we can at least close this item out :).

if you know how to pull the 1.5.0 branch, you're welcome to do so and test the new emissary  code.

**Closed** 2017-10-03 04:04 UTC
Labels: enhancement

**Comment by Daeveren** [comment] 2017-10-03 04:23
I'd completely switch to 1.5 branch for the experimental features, but does the 1.5 branch includes all the changes made to the normal branch? As in, does the 1.5 branch got the new Argus world boss tracking code from yesterday?

**Comment by chancedj** [comment] 2017-10-03 04:31
yup!  it's in sync w/ the new bosses.  i sync'd those back from master to 1.5 today.
