### ISSUE TITLE
Error with latest build

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#59] opened 2017-10-19 06:17 UTC
Master branch, 1.5, latest commit d2940cb

![2017-10-19 09_15_49-greenshot](https://user-images.githubusercontent.com/6321337/31756746-4adbc130-b4ae-11e7-8f65-67ca164fb7b2.png)

**Comment by chancedj** [comment] 2017-10-19 14:03
I think this is a bug that i had in the dev branch that was resolved - but has no conversion mechanism because I wasn't expecting to convert dev data structs to prod.  I'm going to check on this after the emissaries refresh today.

Before 1.6 goes out i plan to also make the change we discussed in the other issue where the buildiing will not happen if the box to show is not checked.

**Comment by chancedj** [comment] 2017-10-19 14:49
sorry, haven't started 1.6.0 yet!  wanted to give this a few days to settle in.  I just meant i would get to the change before 1.6 :).  Currently master is the only active branch.

**Comment by Daeveren** [comment] 2017-10-19 15:01
So does this mean we currently can't use 1.5 anymore? Because the one and only 1.5 commit on master doesn't work (completely breaks the addon) and there are no longer any prior commits of 1.5 (since the whole 1.5 beta branch was deleted).

**Comment by chancedj** [comment] 2017-10-19 17:24
I released 1.5.0 (squished to 1 commit).  when i did so i removed the branch.  What i'm saying is the problem you are seeing is because you used a dev copy of 1.5.  There was a bug with how i was storing the data and when i fixed it i didn't include a "conversion" routine for the bug.  What you are seeing, i believe, is caused by that bug.

Basically if you go from 1.4.x -> 1.5.0 you're fine.
if you go from 1.5.0 (dev) -> 1.5.0 (release) you'll need to reset the db this time.

In the meantime, if i can get to a fix tonight, i'll fix it so that when you choose to hide a section it skips trying to build that section.  Only when you choose to show will it build the data (for example - emissaries).  That will go out in 1.5.1

If you can, run this.  it will clear your emissarry cache of the bad data:

/run for rk, rd in next, LockoutDb do for ck, cd in next, rd do cd.emissaries = {}; end end

**Comment by Daeveren** [comment] 2017-10-19 19:39
Yes it worked, cheers! Should have said, I could delete the saved variables anyway. Awesome, the currency filter is there too! :D

**Comment by chancedj** [comment] 2017-10-19 20:21
great! :).  i haven't had anyone else report any issues so i'm goign to close this one out.  again, appreciate all the help :).

**Closed by chancedj** 2017-10-19 20:21 UTC
Labels: bug
